"""Run OpenVSP AngelScript for /api/analyze with VSPAero-tolerant exit handling."""

from __future__ import annotations

import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

from openvsp_mcp.core import OPENVSP_BIN

_OK_EXIT_CODES = {0, 96, 160, 224}


@dataclass(frozen=True)
class ScriptRunResult:
    script_path: str
    returncode: int
    stdout: str
    stderr: str
    vspaero_ran: bool


def _ensure_statement(command: str) -> str:
    stripped = command.strip()
    if not stripped.endswith(";"):
        stripped = f"{stripped};"
    return stripped


def _write_script(geometry_file: str, commands: list[str], working_dir: Path) -> Path:
    script_path = working_dir / "automation.vspscript"
    lines = [
        "// Auto-generated by openvsp-railway",
        "void main() {",
        "    ClearVSPModel();",
        f'    ReadVSPFile("{geometry_file}");',
    ]
    for command in commands:
        lines.append(f"    {_ensure_statement(command)}")
    lines.extend(
        [
            "    Update();",
            f'    SetVSP3FileName("{geometry_file}");',
            f'    WriteVSPFile("{geometry_file}", SET_ALL);',
            "}",
        ]
    )
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return script_path


def _decode(data: bytes) -> str:
    return data.decode("utf-8", errors="ignore").strip()


def vspaero_completed(output: str) -> bool:
    lowered = output.lower()
    return "total setup and solve time:" in lowered and lowered.rstrip().endswith("done")


def run_openvsp_script(
    geometry_file: str,
    commands: list[str],
    *,
    vspaero_expected: bool = False,
) -> ScriptRunResult:
    geom_path = Path(geometry_file)
    work_parent = geom_path.parent if geom_path.parent.exists() else Path(os.environ.get("RESULTS_DIR", "/data/results"))

    with tempfile.TemporaryDirectory(prefix="openvsp_railway_") as tmpdir:
        script_path = _write_script(geometry_file, commands, Path(tmpdir))
        # Keep a copy for debugging alongside geometry output.
        persisted = work_parent / f".last-{geom_path.stem}.vspscript"
        persisted.write_text(script_path.read_text(encoding="utf-8"), encoding="utf-8")

        try:
            proc = subprocess.run(
                [OPENVSP_BIN, "-script", str(script_path)],
                check=False,
                capture_output=True,
                cwd=str(work_parent),
                timeout=int(os.environ.get("VSP_SCRIPT_TIMEOUT", "600")),
            )
        except FileNotFoundError as exc:
            raise RuntimeError(f"OpenVSP binary not found: {OPENVSP_BIN}") from exc
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError("OpenVSP script timed out") from exc

    stdout = _decode(proc.stdout)
    stderr = _decode(proc.stderr)
    combined = "\n".join(part for part in (stderr, stdout) if part)

    if proc.returncode in _OK_EXIT_CODES:
        return ScriptRunResult(
            script_path=str(persisted),
            returncode=proc.returncode,
            stdout=stdout,
            stderr=stderr,
            vspaero_ran=vspaero_expected,
        )

    if vspaero_expected and vspaero_completed(combined):
        return ScriptRunResult(
            script_path=str(persisted),
            returncode=proc.returncode,
            stdout=stdout,
            stderr=stderr,
            vspaero_ran=True,
        )

    message = stderr or stdout or f"OpenVSP script failed (exit {proc.returncode})"
    if len(message) > 4000:
        message = message[:4000] + "\n... (truncated)"
    raise RuntimeError(message)
